In [2]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

1. Across fine grain cell types

In [1]:
cna_dir = '/data/srlab/ssg34/SLE_kidney_v2/sugiarto_scripts/CNA_chronicityPT/cna_results/'

In [9]:
ctypes_short = list.dirs(cna_dir, full.names = FALSE)

ctypes_short = setdiff(ctypes_short, c(''))
ctypes_short

[1] "b_plasma" "DN"       "GLOM"     "INTL"     "LOH"      "myeloid"  "PT"
[8] "t_nk"

In [ ]:
for (ctype in ctypes_short) {
    
}

In [18]:
ctype = 't_nk'

In [29]:
ncorr_chronicity = read_csv(paste0(cna_dir, ctype, '/Final_Chronicity_none_ncorr.csv'), col_names = c('ncorr_chronicity'))

Rows: 31561 Columns: 1
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (1): ncorr_chronicity

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [30]:
ncorr = ncorr_chronicity

In [36]:
fdrs = read_csv(paste0(cna_dir, ctype, '/Final_Chronicity_none_fdrs.csv'), 
               col_names = c('threshold', 'fdr', 'ncells'))

Rows: 300 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (3): threshold, fdr, ncells

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [37]:
fdr <- fdrs %>% 
            filter(fdr < 0.05) %>% 
            mutate(fdr = round(fdr, 4)) %>% 
            filter(fdr == max(fdr)) %>% 
            pull(threshold)

In [39]:
ncorr-

      ncorr_chronicity
1      0.311656631
2     -0.185044305
3     -0.073240884
4      0.024033708
5      0.122905451
6      0.061787018
7      0.042124935
8      0.094240974
9      0.147367270
10     0.037720529
11     0.004146243
12     0.172204564
13     0.184835322
14     0.142474879
15     0.169081792
16     0.132852333
17    -0.018286270
18     0.109813976
19     0.292789102
20     0.223918928
21     0.204799822
22     0.142858024
23     0.109215829
24     0.097982136
25     0.074316874
26     0.022396625
27     0.289226723
28     0.055254463
29     0.094098486
30     0.106782056
⋮     ⋮
31532  0.16734204
31533  0.14927140
31534  0.08799235
31535  0.08686202
31536 -0.09905372
31537  0.17484865
31538  0.16041331
31539  0.10249027
31540 -0.14523191
31541  0.05642553
31542 -0.06204471
31543 -0.19129867
31544  0.11506914
31545 -0.15548844
31546  0.08617138
31547 -0.11655442
31548 -0.13143440
31549  0.10459562
31550 -0.16653600
31551  0.15157460
31552  0.09639410
31553  0.15469943
31554 -0.12583420
31555 -0.12040266
31556 -0.03004342
31557  0.13876246
31558  0.10985392
31559 -0.09531654
31560  0.02373637
31561 -0.11377247

In [ ]:
ncorr_thresh = abs()

mutate(ncorr_thresh = ifelse(abs(meta$ncorr) > fdr, ncorr, NA))

In [38]:
fdr

[1] 0.3383217

In [25]:
ncorr_pt = read_csv(paste0(cna_dir, ctype, '/injured_pt_prop_none_ncorr.csv'), col_names = c('ncorr_pt'))

Rows: 31561 Columns: 1
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (1): ncorr_pt

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [27]:
ncorr_pt

      ncorr_pt
1      0.191338752
2     -0.163959158
3     -0.026877943
4      0.188643341
5      0.123577534
6     -0.008465415
7     -0.136528846
8      0.159122699
9     -0.028032812
10     0.144927491
11     0.061607022
12     0.190545395
13     0.135017004
14    -0.030061452
15     0.118951806
16     0.123804342
17    -0.100393914
18     0.133817858
19     0.271237676
20     0.241781672
21     0.156963941
22     0.294616373
23     0.112227481
24     0.099605554
25    -0.020441522
26    -0.034595307
27     0.164172403
28     0.038662744
29    -0.077723502
30     0.075895288
⋮     ⋮
31532  0.205814466
31533  0.229219477
31534  0.288998694
31535  0.224677328
31536  0.073759628
31537  0.179569310
31538  0.207097715
31539  0.255385057
31540 -0.067192445
31541  0.028956520
31542  0.024359589
31543  0.020966313
31544  0.179284165
31545 -0.065089588
31546  0.171635310
31547 -0.018799409
31548  0.019692322
31549  0.256892921
31550  0.003293135
31551  0.250238296
31552  0.182319377
31553  0.290003447
31554 -0.007739545
31555 -0.002374455
31556 -0.132663003
31557  0.309828900
31558  0.211273796
31559  0.028874102
31560  0.200998785
31561 -0.019165509